</div>

<div class="page"><div id="footer"><h1>Copyright © <?php echo $author; ?></h1><h2><?php echo strftime('%Y'); ?></h2><h2><a href="https://github.com/goobemaster/php-simple-blog">Generated by: PHP-Simple-Blog</a></h2><h2><a href="http://www.codeigniter.com/">MVC Framework: CodeIgniter</a></h2><h2><a href="http://icons8.com/license/">Free icons: Icons8.com</a></h2></div></div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

</body>
</html>