</div>

<div class="page"><div id="footer"><h1>Copyright © <?php echo $author; ?></h1><h2><?php echo strftime('%Y'); ?></h2><h2><a href="https://github.com/goobemaster/php-simple-blog">Generated by: PHP-Simple-Blog</a></h2><h2><a href="http://www.codeigniter.com/">MVC Framework: CodeIgniter</a></h2><h2><a href="http://icons8.com/license/">Free icons: Icons8.com</a></h2></div></div>

</body>
</html>